filter:
  Obs_qual: [0, 1, 10]
  MarsTime:
    Start:
      MY: 29
      Ls: 10
    Stop: 
      MY: 29
      Ls: 10.2

bin:
  L_s:
    Start: 0
    Stop: 360
    Step: 5
  Profile_lat:
    Start: -90
    Stop: 90
    Step: 15
  Profile_lon:
    Start: -180
    Stop: 180
    Step: 15
  Day: True
  Alt:
    Start: 0
    Stop: 110
    Step: 5
  
ddr2_fields: ["Pres", "T", "T_err", "H2O_ice", "H2O_ice_err", "Dust", "Dust_err"]